### ISSUE TITLE
cest plotting bug

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/chemex#10]
Version 0.6.0dev

While running n_iph cest (including example), I receive this error during plotting:

	Plotting Data
	=============
	
	File(s):
	  * output/global/plots/n_iph_cest_13hz_500ms_499mhz_1c.pdf [.fit]
	Traceback (most recent call last):
	  File "<dir>/bin/chemex", line 9, in <module>
	    load_entry_point('chemex==0.6.0dev', 'console_scripts', 'chemex')()
	  File "<dir>/lib/python/site-packages/chemex-0.6.0dev-py2.7.egg/chemex/__main__.py", line 191, in main
	    output_dir
	  File "<dir>/lib/python/site-packages/chemex-0.6.0dev-py2.7.egg/chemex/__main__.py", line 151, in fit_write_plot
	    plot_results(par_fit, par_indexes, par_fixed, data, output_dir)
	  File "<dir>/lib/python/site-packages/chemex-0.6.0dev-py2.7.egg/chemex/__main__.py", line 127, in plot_results
	    output_dir=output_dir_plot)
	  File "<dir>/lib/python/site-packages/chemex-0.6.0dev-py2.7.egg/chemex/plotting.py", line 17, in plot_data
	    plot(dataset, par, par_names, par_fixed, output_dir)
	  File "<dir>/lib/python/site-packages/chemex-0.6.0dev-py2.7.egg/chemex/experiments/cest/plotting.py", line 150, in plot_data
	    with PdfPages(name_pdf) as file_pdf, open(name_txt, 'w') as file_txt:
	AttributeError: __exit__

**Comment by gbouvignies** [comment]
This should work with matplotlib >= 1.3.1 (see http://stackoverflow.com/questions/21933904/matplotlib-pdf-savefig-exiting-early).
Not sure whether I should  modify the code or enforce 1.3.1 in setup.py...

**Comment by viochemist** [comment]
Oy ... seems I'm only running 1.1.1 on Mac. port doesn't update further. I'll see how tough it is to get 1.3.1 ...

**Comment by gbouvignies** [comment]
Have you tried Homebrew instead of port? Works great.
http://brew.sh/

**Comment by viochemist** [comment]
I just tried homebrew ... "brew install matplotlib" didn't do anything

**Comment by viochemist** [comment]
Anyways, I'm on the dev branch now (v 1.5.dev1) from cloning matplotlib off of git. Plotting works fine now.

**Comment by michaellatham77** [comment]
I guess this means matplotlib >=1.3.1 should be enforced.

**Comment by viochemist** [comment]
I'm going to close this issue. I don't see the problem anymore, I don't think.
