### ISSUE TITLE
pydantic error

### ISSUE THREAD

**Issue by gpmejias** [gbouvignies/ChemEx#195]
I have installed chemex using Anaconda in a dedicated environment. The information of the environment is as follow:

```
     active environment : chemex
    active env location : C:\Users\XX\.conda\envs\chemex
            shell level : 2
       user config file : C:\Users\XX\.condarc
 populated config files : C:\Users\XX\.condarc
                          C:\Users\XX\.conda\envs\chemex\.condarc
          conda version : 23.7.2
    conda-build version : 3.26.0
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
```

Hovewer, when I tried to run it, it produces the following error.

Error message: 

```
(chemex) C:\opt>chemex --help
Traceback (most recent call last):
  File "C:\Users\XX\.conda\envs\chemex\Scripts\chemex-script.py", line 5, in <module>
    from chemex.chemex import main
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\chemex\chemex.py", line 7, in <module>
    from chemex.cli import build_parser
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\chemex\cli.py", line 9, in <module>
    from chemex.tools.pick_cest import pick_cest
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\chemex\tools\pick_cest\__init__.py", line 1, in <module>
    from .cest_picker import pick_cest
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\chemex\tools\pick_cest\cest_picker.py", line 12, in <module>
    from chemex.configuration.methods import Selection
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\chemex\configuration\methods.py", line 49, in <module>
    class Method(BaseModel):
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_model_construction.py", line 183, in __new__
    complete_model_class(
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_model_construction.py", line 517, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\main.py", line 584, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 501, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 761, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 574, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 574, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 925, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1047, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1749, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1730, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 766, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 849, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 873, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1117, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 501, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 766, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 845, in match_type
    return self._apply_annotations(source_type, annotations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1749, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1831, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_std_types_schema.py", line 316, in __get_pydantic_core_schema__
    items_schema = handler.generate_schema(self.item_source_type)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 96, in generate_schema
    return self._generate_schema.generate_schema(__source_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 501, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 766, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 849, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 873, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1117, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 501, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 746, in _generate_schema_inner
    return self._annotated_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1681, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1749, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1831, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\functional_validators.py", line 156, in __get_pydantic_core_schema__
    schema = handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1730, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 766, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 853, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\.conda\envs\chemex\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 397, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'chemex.parameters.spin_system.spin_system.SpinSystem'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.6/u/schema-for-unknown-type
```
I would appreciate any kind of assistance.

**Comment by Tejaswi-23** [comment]
Hi,
I have the same issue. When I just tried with -h flag it popup the same error

**Comment by gpmejias** [comment]
I have partially solved the problem by installing an older version (2022.0.0). If I try to install a newer version, I have the previous error.

**Comment by gbouvignies** [comment]
Thank you for bringing this to my attention. I've updated the code to address the issue you reported. Could you please test the updated version in the main branch? For testing, you can install it in a new environment using pip:
```bash
pip install chemex@git+https://github.com/gbouvignies/ChemEx
```
Your feedback would be greatly appreciated to ensure the fix resolves the issue effectively.

**Comment by gpmejias** [comment]
I have test the updated version and it is working fine!

Thank you!
