### ISSUE TITLE
Fitting errors in Chemex v2024.05.2 with MC and BS syntaxes

### ISSUE THREAD

**Issue by cpmgnmr** [gbouvignies/ChemEx#244]
I got the following errors when fitting CPMG relaxation dispersion data using Chemex v2024.05.2.
 
Error 1:
I wanted to run Chemex fitting using the following command, but I have an error in STEP2. Please note that there was no issue when I ran chemex fitting without MC and BS syntaxes, for example, by removing STEP2 from the following method file.
 
chemex fit -e Experiments\600mhz.toml Experiments\800mhz.toml -m Method\method.toml -p Parameters\parameters.toml -o Output
 
The method.toml (below) was prepared using the instructions described on your GitHub page.
 
https://github.com/gbouvignies/ChemEx/blob/main/website/docs/user_guide/fitting/method_files.md
 
https://github.com/search?q=repo%3Agbouvignies%2FChemEx%20mc&type=code
 

Error 2:
Not sure why “--bs"  or “--mc" commands are considered as unrecognized arguments in the latest version of Chemex. Please find the errors below. Please note “--mc 10” also does have a similar error.
chemex fit -e Experiments\600mhz.toml Experiments\800mhz.toml -p Parameters\parameters.toml --bs 10 -o Output
chemex: error: unrecognized arguments: --bs 10

**Comment by viochemist** [comment]
Well, for error 2, the short answer is that syntax isn't supported anymore. Statistics should be specified in the method as detailed in the other file you linked to.

That said, I'm not sure why that one isn't working. What error are you getting in "Error 1"?

**Comment by gbouvignies** [comment]
Hi Biswa and Alex,

Indeed, the syntax of error 2 is no longer supported.

For the record, here is the traceback related to error 1:

```bash
Traceback (most recent call last):
  File "/Users/gbouvignies/Code/ChemEx/.venv/bin/chemex", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/gbouvignies/Code/ChemEx/chemex/chemex.py", line 86, in main
    args.func(args)
  File "/Users/gbouvignies/Code/ChemEx/chemex/chemex.py", line 74, in run
    run_fit(args, experiments)
  File "/Users/gbouvignies/Code/ChemEx/chemex/chemex.py", line 39, in run_fit
    run_methods(experiments, methods, args.output, args.plot)
  File "/Users/gbouvignies/Code/ChemEx/chemex/optimize/fitting.py", line 166, in run_methods
    _fit_groups(
  File "/Users/gbouvignies/Code/ChemEx/chemex/optimize/fitting.py", line 115, in _fit_groups
    _run_statistics(
  File "/Users/gbouvignies/Code/ChemEx/chemex/optimize/fitting.py", line 68, in _run_statistics
    exp_stat = generate_exp_for_statistics(experiments, statistic_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gbouvignies/Code/ChemEx/chemex/containers/experiments.py", line 260, in generate_exp_for_statistics
    return generators[statistic_name](experiments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gbouvignies/Code/ChemEx/chemex/containers/experiments.py", line 206, in generate_monte_carlo_experiments
    experiments_mc.add(experiment.monte_carlo())
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gbouvignies/Code/ChemEx/chemex/containers/experiment.py", line 100, in monte_carlo
    profiles = [profile.monte_carlo() for profile in self.profiles]
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gbouvignies/Code/ChemEx/chemex/containers/profile.py", line 118, in monte_carlo
    profile = deepcopy(self)
              ^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 143, in deepcopy
    y = copier(memo)
        ^^^^^^^^^^^^
  File "/Users/gbouvignies/Code/ChemEx/.venv/lib/python3.12/site-packages/pydantic/main.py", line 760, in __deepcopy__
    _object_setattr(m, '__dict__', deepcopy(self.__dict__, memo=memo))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 259, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 162, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 253, in _reconstruct
    y = func(*args)
        ^^^^^^^^^^^
  File "/Users/gbouvignies/Code/ChemEx/chemex/parameters/spin_system/group.py", line 116, in __hash__
    return hash(self.name)
                ^^^^^^^^^
  File "/Users/gbouvignies/Code/ChemEx/chemex/parameters/spin_system/group.py", line 67, in name
    number = "" if self.number == NO_NUMBER else self.number
                   ^^^^^^^^^^^
AttributeError: 'Group' object has no attribute 'number'
```

The error is related to some operations involving the deepcopy of a `Group` object. The reason behind the error is not entirely clear to me but seems related to what's described in [this discussion](https://stackoverflow.com/questions/46283738/attributeerror-when-using-python-deepcopy). I can solve it by implementing the `__deepcopy__` method in the affected class.
