### ISSUE TITLE
negative R2s / parameter limits ignored

### ISSUE THREAD

**Issue by chriswaudby** [gbouvignies/ChemEx#27]
Hi,

I've got an issue with some CEST and CPMG fitting. I'm finding that occasionally fit crash with the error:
```
Traceback (most recent call last):
  File "/Users/chris/anaconda/envs/chemex/bin/chemex", line 11, in <module>
    load_entry_point('chemex', 'console_scripts', 'chemex')()
  File "/Users/chris/git/chemex/chemex/chemex.py", line 157, in main
    params = fit_write_plot(args, params, data, output_dir)
  File "/Users/chris/git/chemex/chemex/chemex.py", line 116, in fit_write_plot
    params = fitting.run_fit(args.method, params, data)
  File "/Users/chris/git/chemex/chemex/fitting.py", line 39, in run_fit
    result = minimizer.minimize(params=c_params)
  File "/Users/chris/anaconda/envs/chemex/lib/python3.5/site-packages/lmfit/minimizer.py", line 1242, in minimize
    return function(**kwargs)
  File "/Users/chris/anaconda/envs/chemex/lib/python3.5/site-packages/lmfit/minimizer.py", line 1072, in leastsq
    lsout = scipy_leastsq(self.__residual, vars, **lskws)
  File "/Users/chris/anaconda/envs/chemex/lib/python3.5/site-packages/scipy/optimize/minpack.py", line 387, in leastsq
    gtol, maxfev, epsfcn, factor, diag)
  File "/Users/chris/anaconda/envs/chemex/lib/python3.5/site-packages/lmfit/minimizer.py", line 371, in __residual
    out = _nan_policy(out, nan_policy=self.nan_policy)
  File "/Users/chris/anaconda/envs/chemex/lib/python3.5/site-packages/lmfit/minimizer.py", line 1432, in _nan_policy
    raise ValueError("The input contains nan values")
```

I added some debugging code to dump parameters on this error, and the crash looks like an overflow from a massively negative R2 value:
```
('__n_r2_c_n____r_104n_r____t_37__point__5_t____b_800__point__1_b__',
  <Parameter '__n_r2_c_n____r_104n_r____t_37__point__5_t____b_800__point__1_b__', -5865.3896103458328, bounds=[-inf:inf]>)
```

I added in some parameter bounds in my parameters file to try and avoid this issue:
```
r2_a            = 10.0 [5, 50]   ;in s^-1
r2_b            = 10.0 [5, 50]
r2_c            = 10.0 [5, 50]
```

However, I still get the same crash, with negative parameters. When I examine the parameter dump it seems the bounds for state A are being respected but the bounds for the second and third states haven't been parsed or have been reset:
```
('__n_r2_a_n____r_104n_r____t_37__point__5_t____b_800__point__1_b__',
  <Parameter '__n_r2_a_n____r_104n_r____t_37__point__5_t____b_800__point__1_b__', 7.1813557193376631, bounds=[5.0:50.0]>),
('__n_r2_b_n____r_104n_r____t_37__point__5_t____b_800__point__1_b__',
  <Parameter '__n_r2_b_n____r_104n_r____t_37__point__5_t____b_800__point__1_b__', 29.192100993005784, bounds=[-inf:inf]>),
('__n_r2_c_n____r_104n_r____t_37__point__5_t____b_800__point__1_b__',
  <Parameter '__n_r2_c_n____r_104n_r____t_37__point__5_t____b_800__point__1_b__', -5865.3896103458328, bounds=[-inf:inf]>),
```

Any ideas?

Best,

Chris

**Comment by reneeotten** [comment]
that is strange indeed.... If you don't set boundaries the minimum for `r2_i` parameters should be set to 0.0 already (see the function `create_default_params` in the appropriate basis). Why it doesn't seem to accept your boundaries for anything other than r2_a is another weird thing that I cannot explain. Are you combining the CPMG and CEST data together in one fit or does this also happen for the individual data sets? Also, which experiment types do you use "cest.ip" and "cw"? 

Today my Thanksgiving turkey needs some attention, but I was planning to look at some other things in the coming days so I'll see if I can find the problem.

**Comment by chriswaudby** [comment]
Hi Renee,

The problem is the same for CEST and CPMG. I’ve just checked and the error in setting parameter limits (if not the crash itself) happens when using just a single experiment - cest.ip and cpmg.cw.

Happy thanksgiving!

Chris

**Comment by gbouvignies** [comment]
Hi Chris,

I don't seem to be able to reproduce the behaviour using the example in `examples/CEST/N15_InPhase`. Could you attach some config files (experiment.cfg, parameters.cfg, method.cfg, ...) for which the bug appears?

**Comment by chriswaudby** [comment]
OK, just checked and I don’t see it with that example either - but I do see it for `examples/CEST/N15_InPhase_3States`. I've added some code in `datasets/calculate_residuals` to dump the parameters at each step:
```python
if change < -threshold:
    nvarys = len([param for param in params.values() if param.vary])
    redchi = chisq / (self.ndata - nvarys)

    print("  * {:.3e} / {:.3e}".format(chisq, redchi))
                
    print("Parameters:")
    import pprint
    pprint.pprint(params)
```

and when I run the three-state CEST example I get:

```
 step 1 
--------

[NUC->13N, T->1.0C]
Chi2 / Reduced Chi2:
  * 2.234e+03 / 1.861e+01
Parameters:
Parameters([('__n_pb_n____t_1__point__0_t__',
             <Parameter '__n_pb_n____t_1__point__0_t__', value=0.01 (fixed), bounds=[0.0:1.0]>),
            ('__n_pc_n____t_1__point__0_t__',
             <Parameter '__n_pc_n____t_1__point__0_t__', value=0.0050000000000000001 (fixed), bounds=[0.0:1.0]>),
            ('__n_kex_ab_n____t_1__point__0_t__',
             <Parameter '__n_kex_ab_n____t_1__point__0_t__', value=200.0 (fixed), bounds=[0.0:inf]>),
            ('__n_kex_ac_n____t_1__point__0_t__',
             <Parameter '__n_kex_ac_n____t_1__point__0_t__', value=0.0 (fixed), bounds=[0.0:inf]>),
            ('__n_kex_bc_n____t_1__point__0_t__',
             <Parameter '__n_kex_bc_n____t_1__point__0_t__', value=4000.0 (fixed), bounds=[0.0:inf]>),
            ('__n_dw_ab_n____r_13n_r____t_1__point__0_t__',
             <Parameter '__n_dw_ab_n____r_13n_r____t_1__point__0_t__', 4.226, bounds=[-inf:inf]>),
            ('__n_dw_ac_n____r_13n_r____t_1__point__0_t__',
             <Parameter '__n_dw_ac_n____r_13n_r____t_1__point__0_t__', 4.226, bounds=[-inf:inf]>),
            ('__n_cs_a_n____r_13n_r____t_1__point__0_t__',
             <Parameter '__n_cs_a_n____r_13n_r____t_1__point__0_t__', value=108.20699999999999 (fixed), bounds=[-inf:inf]>),
            ('__n_r2_a_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__',
             <Parameter '__n_r2_a_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__', 10.0, bounds=[0.0:inf]>),
            ('__n_r1_a_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__',
             <Parameter '__n_r1_a_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__', 1.2999999999999998, bounds=[0.0:inf]>),
            ('__n_cs_b_n____r_13n_r____t_1__point__0_t__',
             <Parameter '__n_cs_b_n____r_13n_r____t_1__point__0_t__', 112.43299999999999, bounds=[-inf:inf], expr='__n_cs_a_n____r_13n_r____t_1__point__0_t__ + __n_dw_ab_n____r_13n_r____t_1__point__0_t__'>),
            ('__n_r2_b_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__',
             <Parameter '__n_r2_b_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__', 10.0, bounds=[-inf:inf], expr='__n_r2_a_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__'>),
            ('__n_r1_b_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__',
             <Parameter '__n_r1_b_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__', 1.2999999999999998, bounds=[0.0:inf], expr='__n_r1_a_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__'>),
            ('__n_cs_c_n____r_13n_r____t_1__point__0_t__',
             <Parameter '__n_cs_c_n____r_13n_r____t_1__point__0_t__', 112.43299999999999, bounds=[-inf:inf], expr='__n_cs_a_n____r_13n_r____t_1__point__0_t__ + __n_dw_ac_n____r_13n_r____t_1__point__0_t__'>),
            ('__n_r2_c_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__',
             <Parameter '__n_r2_c_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__', 10.0, bounds=[-inf:inf], expr='__n_r2_a_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__'>),
            ('__n_r1_c_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__',
             <Parameter '__n_r1_c_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__', 1.2999999999999998, bounds=[0.0:inf], expr='__n_r1_a_n____r_13n_r____t_1__point__0_t____b_499__point__2_b__'>)])
```

It looks like the bounds are applied for the first state R2, but not the others?

**Comment by gbouvignies** [comment]
The `set` method of `lmfit.Parameter` object resets bounds when an expression is set. I changed the code in `cest.ip` and `cpmg.cw` to enforce the bounds on `r2` parameters for 3-state fit. Let me know if that solves your issue.

**Comment by chriswaudby** [comment]
Yep, that's done the trick. Thanks!

**Comment by chriswaudby** [comment]
Hi,

Sorry to re-open this issue, but on closer inspection the fix doesn't seem to work entirely. With the fix, the R2 min and max are set to [0, +inf] rather than [-inf, +inf], which is good (and temporarily solved my problem), but any limits that are specified in the parameters file are still ignored.

e.g. in `examples/CPMG/N15_CW` I modified the parameter file to:
```
r2_a, B0->500.0MHz  = 10.0 [1, 50]         ;in s^-1
r2_a, B0->800.0MHz  = 10.0 [2, 51]         ;in s^-1
r2_b = 10.0 [3,52]
```

If I then dump the output between iterations as before, I see:
```
<Parameter '__n_r2_a_n____r_31n_r____t_25__point__0_t____b_500__point__0_b__', 6.3874215200881137, bounds=[1.0:50.0]>
<Parameter '__n_r2_b_n____r_31n_r____t_25__point__0_t____b_500__point__0_b__', 6.3874215200881137, bounds=[0.0:inf], expr='__n_r2_a_n____r_31n_r____t_25__point__0_t____b_500__point__0_b__'>
<Parameter '__n_r2_a_n____r_31n_r____t_25__point__0_t____b_800__point__0_b__', 8.17787029179655, bounds=[2.0:51.0]>
<Parameter '__n_r2_b_n____r_31n_r____t_25__point__0_t____b_800__point__0_b__', 8.17787029179655, bounds=[0.0:inf], expr='__n_r2_a_n____r_31n_r____t_25__point__0_t____b_800__point__0_b__'>
```
Again, limits for state A seems to be handled correctly, but other states are not.

**Comment by gbouvignies** [comment]
Hi Chris,

There was indeed an issue with the way the function to set bounds behaved with parameters with an `expr`. I believe 562c550 should fix. Let me know if it works as expected for you. Hopefully it does not break the code elsewhere...

**Comment by chriswaudby** [comment]
Thanks, I’ll give it a shot - is this commit on top of the previous fix, which I think was only applied to the cest.ip and cpmg.cw experiments?

**Comment by reneeotten** [comment]
Yeah, I have been fiddling around with lmfit a bit as well and it's a bit tricky to set these things properly... I personally don't like to "hack" in the profile/*.py files where the R2 values are now treated differently. Hopefully once we have figured out the lmfit way of setting parameters, we can hopefully clean up some more.

In case the consensus is that the default expression for r2_b / r2_c should be related to r2_a then this should be done in the create_default_params() function in the bases/*.py files. Or am I missing something here?
