### ISSUE TITLE
examples failed after install

### ISSUE THREAD

**Issue by Gerardwx** [gbouvignies/ChemEx#58]
I was unable to successfully run the CEST_CH3_1H_IP_AP and CPMG_CH3_M examples.

CEST_CH3_1H_IP_AP trace:
`Traceback (most recent call last):
  File "/usr/software/chemex/bin/chemex", line 8, in <module>
    sys.exit(main())
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/chemex.py", line 41, in main 
    args.func(args)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/chemex.py", line 68, in run
    _run_fit(args, defaults, experiments, params) 
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/chemex.py", line 76, in _run_fit
    fitter.run_methods(params)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/fitting.py", line 82, in run_methods
    g_params = self._fit_groups(
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/fitting.py", line 121, in _fit_groups
    coh.post_fit(
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/helper.py", line 9, in post_fit
    _print_chisqr(experiments, params) 
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/helper.py", line 40, in _print_chisqr
    statistics = calculate_statistics(experiments, params) 
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/helper.py", line 46, in calculate_statistics
    residuals = experiments.residuals(params)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/experiment.py", line 31, in residuals
    list( 
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/experiment.py", line 33, in <genexpr>
    experiment.residuals(params)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/experiment.py", line 162, in residuals
    return list(
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/experiment.py", line 164, in <genexpr>
    profile.residuals(params) for profile in self._profiles
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/cest.py", line 39, in residuals
    return (self.calculate(params) - data["intensities"]) / data["errors"]
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/cest.py", line 43, in calculate
    par_values = self._get_parvals(params)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/cest.py", line 103, in _get_parvals
    return tuple(
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/cest.py", line 104, in <genexpr>
    (name1, params[name2].value) for name1, name2 in self._pnames.items()
KeyError: '__N_PB_N____R_L7HD1_R__'`

CPMG_CH3_MQ trace:
`Traceback (most recent call last):
  File "/usr/software/chemex/bin/chemex", line 8, in <module>
    sys.exit(main())
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/chemex.py", line 41, in main 
    args.func(args)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/chemex.py", line 68, in run
    _run_fit(args, defaults, experiments, params) 
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/chemex.py", line 76, in _run_fit
    fitter.run_methods(params)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/fitting.py", line 82, in run_methods
    g_params = self._fit_groups(
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/fitting.py", line 121, in _fit_groups
    coh.post_fit(
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/helper.py", line 9, in post_fit
    _print_chisqr(experiments, params) 
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/helper.py", line 40, in _print_chisqr
    statistics = calculate_statistics(experiments, params) 
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/optimize/helper.py", line 46, in calculate_statistics
    residuals = experiments.residuals(params)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/experiment.py", line 31, in residuals
    list( 
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/experiment.py", line 33, in <genexpr>
    experiment.residuals(params)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/experiment.py", line 162, in residuals
    return list(
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/experiment.py", line 164, in <genexpr>
    profile.residuals(params) for profile in self._profiles
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/cpmg.py", line 46, in residuals
    return (self.calculate(params) - data["intensities"]) / data["errors"]
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/cpmg.py", line 50, in calculate
    par_values = self._get_parvals(params)
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/cpmg.py", line 109, in _get_parvals
    return tuple(
  File "/usr/software/chemex/lib/python3.9/site-packages/chemex/containers/cpmg.py", line 110, in <genexpr>
    (name1, params[name2].value) for name1, name2 in self._pnames.items()
KeyError: '__N_R2MQ_A_N____R_L98CD1__MINUS__HD1_R____B_600__POINT__2_B__'
`

[CEST_CH3_1H_IP_AP.log](https://github.com/gbouvignies/ChemEx/files/8333453/CEST_CH3_1H_IP_AP.log)
[CPMG_CH3_MQ.log](https://github.com/gbouvignies/ChemEx/files/8333454/CPMG_CH3_MQ.log)
.

**Comment by gbouvignies** [comment]
Thanks your message, and sorry for the very late reply. I believe this should be fixed now.
